service: automator-api

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    JWT_SECRET: ${env:JWT_SECRET}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:DescribeTable
            - dynamodb:ListTables
            - dynamodb:CreateTable
            - dynamodb:DeleteTable
          Resource: 
            - "arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/Users"
            - "arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/Goals"
            - "arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/Sessions"
            - "arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/Users/index/*"
            - "arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/*"

functions:
  api:
    handler: dist/lambda.handler
    events:
      - http:
          path: /auth/{proxy+}
          method: ANY
          cors: true
      - http:
          path: /app/{proxy+}
          method: ANY
          cors: true
      - http:
          path: /n8n/{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000